---
- name: Create {{github_folder}} folder
  file:
    path: '{{github_folder}}'
    state: directory

- name: Clone git@github.com:{{github_username}}/{{github_repository}}.git
  git:
    repo: git@github.com:{{github_username}}/{{github_repository}}.git
    dest: '{{github_folder}}/{{github_repository}}'
    clone: yes
    accept_hostkey: yes
    update: yes

- name: Set upstream to git@github.com:{{github_upstream}}/{{github_repository}}.git
  shell: git remote add upstream git@github.com:{{github_upstream}}/{{github_repository}}.git
  args:
    chdir: '{{github_folder}}/{{github_repository}}'
  ignore_errors: yes

- name: Config for having pull requests locally
  lineinfile:
    path: '{{github_folder}}/{{github_repository}}/.git/config'
    regexp: '^        fetch = \+refs/pull/\*/head:refs/remotes/upstream/pr/\*'
    insertafter: '^        fetch = +refs/heads/*:refs/remotes/upstream/*'
    line: '        fetch = +refs/pull/*/head:refs/remotes/upstream/pr/*'

- name: Fetch upstream and rebase
  shell: git checkout master && git fetch upstream && git rebase upstream/master
  args:
    chdir: '{{github_folder}}/{{github_repository}}'
  ignore_errors: yes
